version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: ./docker/python/Dockerfile
    container_name: "flask-docker"
    volumes:
      - .:/application
    ports:
      - "8081:8080"
    env_file:
      - .env
    networks:
      - app
    depends_on:
      - db


  db:
    container_name: "database-flask-docker"
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=newbase
      - MYSQL_USER=viktor
      - MYSQL_PASSWORD=14051998
    ports:
      - "5050:3306"
    networks:
      - app

networks:
  app:
    driver: bridge